config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  resources :trips do
    resources :group_members, only: [:new, :create, :destroy, :index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :chat_rooms, only: :show do
    resources :messages, only: :create
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  mount ActionCable.server => "/cable"
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user
  after_create :send_status_email
  after_create :send_respond_to_application_email

  private

  def send_status_email
    UserMailer.status(self).deliver_now
  end

  def send_respond_to_application_email
    UserMailer.respond_to_application(self).deliver_now
  end
end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  before_action :find_group_member, only: [:edit, :update,:show, :reject, :accept, :destroy, :pending_index, :rejected_index, :accepted_index]
  before_action :find_trip, only: [:edit, :update, :pending_index, :rejected_index, :accepted_index, :index]

  def new
    @trip = Trip.find(params[:trip_id])
    @group_member = GroupMember.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @group_member = GroupMember.new(group_member_params)
    @group_member.user = current_user
    @group_member.group = @trip.group
    @group_member.status = "pending"
    render 'new' unless @group_member.save
  end

  def destroy
    @group_member.destroy
  end

  def edit
  end

  def update
    @group_member.update(group_member_params)
    if @group_member.save
      flash[:notice] = 'Status updated'
      redirect_to trip_path(@trip)
    else
      flash[:alert] = 'Could not update status'
    end
  end

  def index
    @group_members = GroupMember.where(group: @trip.group)
  end

  def pending_index
    @pending_members = GroupMember.where(status: "pending", group: @trip.group)
  end
  helper_method :pending_index

  def accepted_index
    @accepted_members = GroupMember.where(status: "accepted", group: @trip.group)
  end
  helper_method :accepted_index

  def rejected_index
    @rejected_members = GroupMember.where(status: "rejected", group: @trip.group)
  end
  helper_method :rejected_index

  private

  def find_trip
    @trip = Trip.find(params[:trip_id])
  end

  def find_group_member
    @group_member = GroupMember.find(params[:id])
  end

  def group_member_params
    params.require(:group_member).permit(:group, :user, :status, :message_to_organiser)
  end
end

app/views/group_members/_index.html.erb
<% if user_signed_in? %>
<% order_paid = true if Order.find_by(user: current_user, trip: @trip, state: 'paid') %>
  <% @order = Order.create!(trip: @trip, amount: (@trip.price/10), state: 'pending', user: current_user) if !order_paid %>
<% end %>
<div class="member-logic">
  <% if user_signed_in? %>


    <% status_members = @trip.group.group_members %>
    <% rejects = [] %>
    <% crews = [] %>
    <% waiting = [] %>
    <% status_members.each do |member| %>
        <% if member.status == "rejected" %>
          <%  @reject = User.find(member.user_id) %>
          <%  rejects << @reject %>
        <% elsif member.status == "accepted" %>
          <%  @crew = User.find(member.user_id) %>
          <%  crews << @crew %>
        <% else member.status == "pending" %>
          <% @waiter = User.find(member.user_id)  %>
          <%  waiting << @waiter %>
        <% end %>
    <% end %>
    <% group = @trip.group.group_members.where(user: current_user) %>

    <% end %>

    <% accepted_members = @trip.group.group_members.where(status: 'accepted') %>

</div>
<h4>The crew</h4>
  <div class="row" >
    <div class="col-sm">
      <p><strong>Pending</strong></p>
      <% pending_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
        <li><%= member.message_to_organiser %></li>
        <li><%= member.status %></li>
      </ul>

      <%= simple_form_for [@trip, member] do |f|%>

        <%= f.input :status, :as => :hidden, :input_html => { :value => "rejected" } %>

        <%= f.submit "reject", class: "btn btn-danger"%>

      <% end %>

      <%= simple_form_for [@trip, member] do |f|%>

        <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" } %>

        <%= f.submit "accept", class: "btn btn-success"%>

      <% end %>
      <% end %>
    </div>

    <div class="col-sm">
      <p><strong>Accepted</strong></p>
      <% accepted_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
      </ul>
      <% end %>
    </div>

    <div class="col-sm">
      <p><strong>Rejected</strong></p>
      <% rejected_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
      </ul>
      <% end %>
    </div>

  </div>
</div>

app/views/group_members/create.html.erb
<div class="show-holder">
  <h3 class="form-header" style="padding: 10px; text-align: center;"><%= @trip.title %> with <%=@trip.user.first_name %></h3>
  <div class ="create">
    <p>Your request has been submitted to <%= @trip.user.first_name %></p>
    <p>While you wait for a response why not...</p>
    <div class="">
      <%= link_to "View all trips", trips_path %>
    </div>
  </div>
</div>

app/views/group_members/index.html.erb
<h1>View the statuses of different group members</h1>


<div class="container">
  <div class="row">
    <div class="col-sm">
      <h2>Pending members</h2>
      <% pending_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
        <li><%= member.message_to_organiser %></li>
        <li><%= member.status %></li>
      </ul>

      <%= simple_form_for [@trip, member] do |f|%>

        <%= f.input :status, :as => :hidden, :input_html => { :value => "rejected" } %>

        <%= f.submit "reject", class: "btn btn-danger"%>

      <% end %>

      <%= simple_form_for [@trip, member] do |f|%>

        <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" } %>

        <%= f.submit "accept", class: "btn btn-success"%>

      <% end %>
      <% end %>
    </div>

    <div class="col-sm">
      <h2>Accepted members</h2>
      <% accepted_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
        <li><%= member.status %></li>
      </ul>
      <% end %>
    </div>

    <div class="col-sm">
      <h2>Rejected members</h2>
      <% rejected_index.each do |member| %>
      <ul>
        <li><%= member.user.first_name %></li>
        <li><%= member.status %></li>
      </ul>
      <% end %>
    </div>

  </div>
</div>

app/views/group_members/new.html.erb
<div class="container w-75">
  <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.2)), url(<%= cl_image_path(@trip.photo, width: 1200, crop: "scale") %>); height: 240px; background-position: center;">
    <h1 mx-8><%= @trip.title %></h1>
  </div>
  <br>
  <br>
  <div class="w-50">

  <h4>Request to join <%= @trip.user.first_name %>'s trip to <%= @trip.destination %> </h4>
  <br>
  <%= @trip.description %>
  <br>
  <%= simple_form_for [@trip, @group_member] do |f|%>
  <br>
  <%= f.input :message_to_organiser, label: "Enter a message to the organiser" %>
  <%= f.submit "Request to join group", class: "btn btn-call-to-action", style: "margin-bottom: 40px;"%>
  <% end %>
  </div>
</div>