config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  resources :trips do
    resources :group_members, only: [:new, :create, :destroy, :index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :chat_rooms, only: :show do
    resources :messages, only: :create
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader

  has_many :group_members, dependent: :destroy
  has_many :user_activities, dependent: :destroy
  has_many :activities, through: :user_activities
  has_many :messages, dependent: :destroy
  has_many :orders


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :location, :dob, presence: true
  validates :first_name, :last_name, length: { minimum: 2, too_short: "Name must be two characters minimum" }
  validates :bio, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :find_user
  def show
  end

  def edit
  end

  def update
    @user.update!(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :location, :dob, :bio)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  # remove skip_before authentication when signup/login flows ready
  skip_before_action :authenticate_user!

  def show
    @planned_trips = Trip.where(user_id: @user)
    @joined_trips = Trip.joins(group: [:group_members]).where(group: { group_members: { user_id: @user } })
    # group.group_members.where(user_id: current_user.id)
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:notice] = 'Profile updated'
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Could not update profile, please try again'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :location, :dob, :bio, :photo)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %>'s profile</h1>

<%= simple_form_for @user, method: "patch" do |f| %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :dob %>
  <%= f.input :location %>
  <%= f.input :bio %>
  <%= f.submit "Edit profile" %>
<% end %>

<%= link_to "Return to profile", user_path(@user) %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="d-flex justify-content-between">
        <div class="profile-content">
          <div class="container-img">
            <div class="top-left"><h4 style="text-align: center; font-size: 35px; padding-top: 5px;">
              <%= link_to edit_user_path(current_user) do %>
                <%= @user.first_name %>
                <%= @user.last_name %>
              <% end %></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="user-info"">
      <br>
      <br>
      <div class="cl-img"
              style="background-image: linear-gradient(180deg,
              rgba(0, 0, 0, 0.5),
              rgba(250, 250, 250, 0.1)), url(<%= cl_image_path(@user.photo, gravity: :auto) %>)">
      </div>
      <div class="profile-text">
        <p style="font-size: 1.7em;"><%= @user.first_name %> from <%= @user.location %></p>
        <div class="bio"><p style="font-size: 1.1em;"><%= @user.bio %></p></div>
          <p style="font-size: 18px;"><strong>Contact me:</strong> <%= @user.email %></p>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-6" style="height: 50px; width: 50%; text-align: center; border: none;">
      <button class="tablinks tablink-left" id="planned_trips_button" style="border: none; "onclick="openTrip(event, 'Organised')">Trips I've Planned</button>
    </div>
    <div class="col-xs-6" style="height: 50px; width: 50%; text-align: center">
      <button class="tablinks inactive tablink-right" id="joined_trips_button" onclick="openTrip(event, 'Joined')">Trips I've Joined</button>
    </div>
  </div>


      <br>
      <br>
        <div class="row tabcontent" id="organised"><% x = -1 %>
          <% @planned_trips.each do |planned| %>
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 trip-column p-3">
            <div id = "profile" class="card trip-card">
              <div class="top">
                <div class="photo-top">
                    <%= cl_image_tag(planned.photo, width: 220, height: 120, crop:"fill") %>
                  <!-- <div class="deposit-status">
                     <p><%# if planned.orders[x] == "paid" %>
                       Deposit paid <i class="fas fa-check-circle"></i>
                    <%# else %>
                    Deposit outstanding <i class="fas fa-exclamation-circle"></i>
                    <%# end %></p>
                    <%# x += 1 %>
                  </div> -->
                </div>
              </div>
              <div class="card-info">
                <div class="title">
                    <%= planned.activity.name %>
                </div>
                <div class="description">
                    <%= planned.title %>
                </div>
                 <div class="title d-flex justify-content-between pr-3">
                <span>
                  <%= planned.start_date.strftime('%b %Y') %>
                </span>
                <span>
                  £<%= planned.price.to_i.round %>pp
                </span>
                <span>
                  Max <%= planned.max_crew_size %> <i class="fas fa-users"></i>
                </span>
              </div>
                     <%= link_to "", trip_path(planned), class: "stretched-link" %>
              </div>
            </div>
          </div>
          <% end %>
        </div>

    <div id="joined" class="row tabcontent d-none">
      <br>
      <br>
          <% y = -1 %>
          <% @joined_trips.each do |joined| %>
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 trip-column p-3">
            <div id = "profile" class="card trip-card profile">
              <div class="top">
                <div class="photo-top">
                    <%= cl_image_tag(joined.photo, width: 220, height: 120, crop:"fill") %>
                  <!-- <div class="deposit-status"> -->
                     <!-- <p><%# if joined.orders[y] == "paid" %> -->
                       <!-- Deposit paid <i class="fas fa-check-circle"></i> -->
                    <%# else %>
                   <!--  Deposit outstanding <i class="fas fa-exclamation-circle"></i> -->
                    <%# end %><!-- </p> -->
                    <%# y += 1 %>
                 <!--   </div>  -->
                </div>
              </div>
                <div class="card-info">
                <div class="title">
                    <%= joined.activity.name %>
                </div>
                <div class="description">
                    <%= joined.title %>
                </div>
                 <div class="title d-flex justify-content-between pr-3">
                <span>
                  <%= joined.start_date.strftime('%b %Y') %>
                </span>
                <span>
                  £<%= joined.price.to_i.round %>pp
                </span>
                <span>
                  Max <%= joined.max_crew_size %> <i class="fas fa-users"></i>
                </span>
              </div>
                     <%= link_to "", trip_path(joined), class: "stretched-link" %>
              </div>
            </div>
            </div>
          <% end %>
    </div>

<!-- tabs -->
<script>
  btnJoinedTrip = document.getElementById('joined_trips_button');
  btnPlannedTrip = document.getElementById('planned_trips_button');
  organized = document.getElementById('organised');
  joined = document.getElementById('joined');

  btnPlannedTrip.addEventListener('click', (event) => {
    btnPlannedTrip.classList.remove('inactive');
    btnJoinedTrip.classList.add('inactive');
    organized.classList.remove('d-none');
    joined.classList.add('d-none');
  });
  btnJoinedTrip.addEventListener('click', (event) => {
    btnJoinedTrip.classList.remove('inactive');
    btnPlannedTrip.classList.add('inactive');
    organized.classList.add('d-none');
    joined.classList.remove('d-none');
  });
         // Window.onLoad= openTrip(event, 'Joined');


         //  function openTrip(evt, tripName) {
         //    var i, tabcontent, tablinks;
         //    tabcontent = document.getElementsByClassName("tabcontent");
         //    for (i = 0; i < tabcontent.length; i++) {
         //      tabcontent[i].style.display = "none";
         //    }
         //    tablinks = document.getElementsByClassName("tablinks");
         //    for (i = 0; i < tablinks.length; i++) {
         //      tablinks[i].className = tablinks[i].className.replace(" active", "");
         //    }
         //    document.getElementById(tripName).style.display = "block";
         //    evt.currentTarget.className += " active";
         //  }

</script>