config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  resources :trips do
    resources :group_members, only: [:new, :create, :destroy, :index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :chat_rooms, only: :show do
    resources :messages, only: :create
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<script>
    const alertFade = () => {
      const alerts = document.querySelectorAll("div.alert");
        alerts.forEach((e) => {
          e.classList.add('fadeout');
        });
      };
</script>


<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <script>
      setTimeout(alertFade,1500);
    </script>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <script>
      setTimeout(alertFade,1500);
    </script>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a href="/">
  <img src="<%= asset_url 'seekers_logo.png' %>">
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link", class: "underline #{params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'altered-navbar'}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create a trip", new_trip_path, class: "underline #{params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'altered-navbar'}" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo? %>
             <%= cl_image_tag current_user.photo.url, crop: :fit, class: "avatar-user dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item p-3">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'altered-navbar'}", class: "underline #{params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'altered-navbar'}" %>
        </li>
        <li class="nav-item p-3">
          <%= link_to "Log in", '#exampleModalCenter', 'data-toggle' => 'modal', class: "underline #{params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'altered-navbar'}" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<!-- Modal log in-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header form-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Log in</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "devise/sessions/new" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>