config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  resources :trips do
    resources :group_members, only: [:new, :create, :destroy, :index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :chat_rooms, only: :show do
    resources :messages, only: :create
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  mount ActionCable.server => "/cable"
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       @order.amount_cents,
      description:  "Deposit payment for #{@order.trip.id} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    flash[:notice] = 'Payment successful!'
    redirect_to trip_path(@order.trip)
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/_new.html.erb
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <strong>Deposit: <%= humanized_money_with_symbol(@order.amount) %></strong>
    </label>
    <p>Pay your deposit to secure your place on the trip. <br> Deposits are refunded on the last day or forfeited in the event of a no-show.</p>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Trip deposit"
    data-email="<%= current_user.email %>"
    data-description="<%= @order.trip.title %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>">

    </script>

<% end %>

app/views/payments/new.html.erb
<h1>Deposit payment for trip <%= @order.trip.id %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Trip deposit"
    data-email="<%= current_user.email %>"
    data-description="Trip <%= @order.trip.id %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>">

    </script>

<% end %>